#!/bin/bash

set -e
set -u
set -f

function forcelink
{
    SRC=$1
    DST=$2
    sudo ln -s -f $SRC $DST
}

wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
sudo cp /vagrant/sources.list /etc/apt/sources.list

# better to do this than put it in sources.list, 
# it offers more flexiblity
echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty main" | sudo tee -a /etc/apt/sources.list

sudo add-apt-repository ppa:george-edison55/cmake-3.x
sudo apt-get update -qq

VERSION="3.9"
sudo apt-get install -y clang-${VERSION} \
    libclang-common-${VERSION}-dev \
    libclang-${VERSION}-dev \
    libclang1-${VERSION} \
    llvm-${VERSION}-dev \
    liblldb-${VERSION}-dev \
    libllvm${VERSION} \
    lldb-${VERSION} \
    llvm-${VERSION} \
    clang-format-${VERSION} \
    python-clang-${VERSION} \
    git-core 

#sudo apt-get install -y cmake \
    #cmake-curses-gui \
    #libc++-dev \
    #libc++abi-dev \
    #bear \
    #scons \
    #python-dev \
    #python-setuptools \
    #python-pip

#pip install ipython[all] --user

forcelink /usr/bin/clang++-${VERSION} /usr/local/bin/clang++
forcelink /usr/bin/clang-${VERSION}  /usr/local/bin/clang
forcelink /usr/lib/llvm-${VERSION}/lib/libclang-${VERSION}.so.1 /usr/local/lib/libclang-${VERSION}.so
forcelink /usr/lib/llvm-${VERSION}/lib/libclang.so.1 /usr/local/lib/libclang.so

if ! grep -Fxq "source /vagrant/bashext.sh" /home/vagrant/.bashrc; then
    echo "source /vagrant/bashext.sh" >> /home/vagrant/.bashrc
fi

